### ISSUE TITLE
Some typos in the notes

### ISSUE THREAD

**Issue by niyoj** [schatto1/LFS201#1]
## What is the issue?
- I started using this repo as a guide to practice LINUX. And I found some typos during this process.
- In the file, [notes_Ch01.md](https://github.com/niyoj/LFS201/blob/master/Ch01-introduction/notes_Ch01.md), on section `1.4 Relationship to LFS101x`, down where the bullets are there is `bach shell scripting` instead of `bash shell scripting`.
- Can you open this issue for some time? I will be posting some more issues if I find some.

**Comment by schatto1** [comment]
Hi @niyoj, 

I appreciate you opening this issue! I must admit, I haven't looked at this repo after creating it two years ago. Feel free to open more issues if you find other typos. You're also welcome to fix them yourself and create a pull request. Thanks!

**Comment by schatto1** [comment]
I fixed this issue in the latest commit.
